#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Source tutorial clean functions

echo "Cleaning case directories and logs..."

# Clean standard time directories and variables
cleanTimeDirectories
rm -rf processor*
rm -rf dynamicCode
rm -rf constant/polyMesh
rm -rf constant/finite-area
rm -rf postProcessing*
rm -f log.*
rm -f log
rm -rf 0
rm -f 0/ccx 0/ccy 0/ccz
rm -f read_paper.py patch_0_org.py

echo "Clean complete."
